Repository minvws/nl-covid19-data-dashboard, pull requests merged in 2021-04, with the labels that each got.

#2494 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: automerge

#2474 Finish the vaccine delivery stacked bar chart
  packages/app/schema/nl/__index.json
  packages/app/schema/nl/vaccine_delivery_per_supplier.json
  packages/app/src/components-styled/stacked-chart/stacked-chart.tsx
  packages/app/src/components-styled/value-annotation.tsx
  packages/app/src/domain/vaccine/vaccine-delivery-area-chart.tsx
  packages/app/src/domain/vaccine/vaccine-delivery-bar-chart.tsx
  packages/app/src/domain/vaccine/vaccine-delivery-tooltip.tsx
  packages/app/src/intl/hooks/use-intl.ts
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
  packages/app/src/pages/landelijk/vaccinaties.tsx
  packages/common/src/types/data.ts
Labels: hold

#2496 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: automerge

#2500 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2501 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2505 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2507 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2508 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2514 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2515 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2522 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2523 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2524 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: automerge

#2527 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2528 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2533 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2537 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2542 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2543 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2544 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2545 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2547 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2548 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2555 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2559 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2561 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2540 Add stock per supplier chart
  packages/app/schema/nl/__index.json
  packages/app/schema/nl/vaccine_delivery_estimate_time_span.json
  packages/app/schema/nl/vaccine_stock.json
  packages/app/src/components-styled/interactive-legend.tsx
  packages/app/src/domain/tested/infected-per-age-group/infected-per-age-group.tsx
  packages/app/src/domain/vaccine/vaccine-stock-per-supplier-chart.tsx
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
  packages/app/src/pages/landelijk/vaccinaties.tsx
  packages/common/src/types/data.ts
Labels: WIP

#2565 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2572 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2573 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2575 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2577 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2578 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2586 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2587 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: automerge

#2591 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2592 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2595 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2599 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2605 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2608 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2611 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2612 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2615 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2620 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2623 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: automerge

#2625 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2626 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2627 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2629 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2633 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2636 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2641 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2644 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2645 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: automerge

#2648 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2649 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2650 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2666 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2674 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2699 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2700 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2701 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2702 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: automerge

#2704 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2709 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2710 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2713 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2714 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2717 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2718 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2722 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2678 Add moving average to hospital admission charts
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
  packages/app/src/pages/gemeente/[code]/ziekenhuis-opnames.tsx
  packages/app/src/pages/landelijk/intensive-care-opnames.tsx
  packages/app/src/pages/landelijk/ziekenhuis-opnames.tsx
  packages/app/src/pages/veiligheidsregio/[code]/ziekenhuis-opnames.tsx
Labels: Awaiting Data

#2677 Add moving average to deceased charts
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
  packages/app/src/pages/gemeente/[code]/sterfte.tsx
  packages/app/src/pages/landelijk/sterfte.tsx
  packages/app/src/pages/veiligheidsregio/[code]/sterfte.tsx
Labels: Awaiting Data

#2724 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2725 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2726 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2731 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2740 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2743 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2747 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2450 [base] Vaccine cims base
  packages/app/src/config/features.ts
  packages/app/src/domain/topical/topical-vaccine-tile.tsx
  packages/app/src/domain/vaccine/vaccine-page-introduction.tsx
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
  packages/app/src/pages/index.tsx
  packages/app/src/pages/landelijk/vaccinaties.tsx
  packages/app/src/pages/landelijk/ziekenhuis-opnames.tsx
  packages/app/src/static-props/get-data.ts
Labels: hold

#2430 Add vaccination per agegroup view
  packages/app/public/images/chevron-down-grey.svg
  packages/app/src/config/features.ts
  packages/app/src/domain/vaccine/components/coverage-progress-bar.tsx
  packages/app/src/domain/vaccine/components/coverage-row.tsx
  packages/app/src/domain/vaccine/vaccine-coverage-per-age-group.tsx
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
  packages/app/src/pages/landelijk/vaccinaties.tsx
Labels: hold
