Repository minvws/nl-covid19-data-dashboard, pull requests merged in 2021-03, with the labels that each got.

#2116 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2117 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2118 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#2130 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2131 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2133 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2134 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2139 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#2140 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2144 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2148 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#2151 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2153 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#2155 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2163 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2165 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2167 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2168 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2169 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#2172 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2173 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#2175 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2176 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2180 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#2181 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#2183 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#2184 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#2188 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2189 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#2190 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2191 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2192 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2195 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2199 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2200 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2204 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#2206 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#2210 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2211 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2213 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2212 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#2216 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#2215 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2218 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#2219 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#2221 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#2230 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#2229 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#2241 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2248 vaccine delivery estimate time span
  packages/app/schema/nl/__index.json
  packages/app/schema/nl/vaccine_delivery_estimate_time_span.json
  packages/common/src/types/data.ts
Labels: hold

#2263 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2269 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2278 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2279 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#2287 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#2288 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#2231 Create municipality sewer choropleth
  packages/app/schema/gm_collection/__index.json
  packages/app/schema/gm_collection/sewer.json
  packages/app/src/components/choropleth/municipal-thresholds.ts
  packages/app/src/components/choropleth/tooltips/municipal/create-sewer-regional-tooltip.tsx
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
  packages/app/src/pages/landelijk/rioolwater.tsx
  packages/common/src/types/data.ts
Labels: hold

#2305 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2306 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2309 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2310 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2315 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2323 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2326 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2327 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2328 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2330 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2336 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2338 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2339 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2345 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2346 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2350 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#2351 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#2356 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#2357 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#2314 Add Schema for G-number
  packages/app/schema/nl/__index.json
  packages/app/schema/nl/g_number.json
  packages/app/schema/vr/__index.json
  packages/app/schema/vr/g_number.json
  packages/common/src/types/data.ts
Labels: hold

#2319 Schema for Vaccinated per age group
  packages/app/schema/nl/__index.json
  packages/app/schema/nl/vaccine_coverage_per_age_group.json
  packages/common/src/types/data.ts
Labels: hold

#2373 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2374 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2375 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#2381 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#2383 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#2385 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2386 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2390 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2393 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#2396 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2398 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2399 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2400 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2401 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2404 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2408 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: automerge

#2409 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: automerge

#2416 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2418 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2420 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: automerge

#2378 Create Stacked area trend
  packages/app/src/components-styled/time-series-chart/components/line-trend.tsx
  packages/app/src/components-styled/time-series-chart/components/series-icon.tsx
  packages/app/src/components-styled/time-series-chart/components/series.tsx
  packages/app/src/components-styled/time-series-chart/components/stacked-area-trend.tsx
  packages/app/src/components-styled/time-series-chart/components/timespan-annotation.tsx
  packages/app/src/components-styled/time-series-chart/components/tooltip/tooltip-series-list.tsx
  packages/app/src/components-styled/time-series-chart/logic/common.ts
  packages/app/src/components-styled/time-series-chart/logic/hover-state.ts
  packages/app/src/components-styled/time-series-chart/logic/legend.tsx
  packages/app/src/components-styled/time-series-chart/logic/series.ts
  packages/app/src/components-styled/time-series-chart/time-series-chart.tsx
Labels: hold

#2429 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2442 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: automerge

#2443 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2446 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: automerge

#2447 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: automerge

#2423 Update vaccine page introduction
  packages/app/src/domain/topical/topical-vaccine-tile.tsx
  packages/app/src/domain/vaccine/vaccine-page-introduction.tsx
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
  packages/app/src/pages/index.tsx
Labels: hold

#2426 Create vaccinated people chart
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
  packages/app/src/pages/landelijk/vaccinaties.tsx
Labels: hold

#2451 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2452 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2362 Add nursing home moving average schema and charts
  packages/app/schema/nl/nursing_home.json
  packages/app/schema/vr/nursing_home.json
  packages/app/src/components-styled/time-series-chart/components/area-trend.tsx
  packages/app/src/components-styled/time-series-chart/components/axes.tsx
  packages/app/src/components-styled/time-series-chart/components/bar-trend.tsx
  packages/app/src/components-styled/time-series-chart/components/chart-container.tsx
  packages/app/src/components-styled/time-series-chart/components/index.ts
  packages/app/src/components-styled/time-series-chart/components/series-icon.tsx
  packages/app/src/components-styled/time-series-chart/components/series.tsx
  packages/app/src/components-styled/time-series-chart/components/tooltip/tooltip-series-list.tsx
  packages/app/src/components-styled/time-series-chart/logic/series.ts
  packages/app/src/components-styled/time-series-chart/time-series-chart.tsx
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
  packages/app/src/pages/landelijk/verpleeghuiszorg.tsx
  packages/app/src/pages/veiligheidsregio/[code]/verpleeghuiszorg.tsx
  packages/app/src/utils/get-trailing-date-range.ts
  packages/common/src/types/data.ts
Labels: hold

#2453 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2454 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2457 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: automerge

#2460 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2461 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2467 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2469 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2471 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2472 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2476 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2481 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2483 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge

#2485 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: automerge
