Repository minvws/nl-covid19-data-dashboard, pull requests merged in 2021-01, with the labels that each got.

#1311 Lokalise: Translations update
  src/locale/en.json
  src/locale/nl.json
Labels: lokalise

#1313 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1314 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1316 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1317 Lokalise: Translations update
  src/locale/nl.json
Labels: lokalise

#1319 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1320 Lokalise: Translations update
  src/locale/en.json
  src/locale/nl.json
Labels: lokalise

#1321 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1322 Lokalise: Translations update
  src/locale/nl.json
Labels: lokalise

#1323 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#1324 Lokalise: Translations update
  src/locale/en.json
  src/locale/nl.json
Labels: lokalise

#1325 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1326 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1329 Lokalise: Translations update
  src/locale/nl.json
Labels: lokalise

#1331 Lokalise: Translations update
  src/locale/en.json
  src/locale/nl.json
Labels: lokalise

#1333 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1338 Lokalise: Translations update
  src/locale/en.json
  src/locale/nl.json
Labels: lokalise

#1344 Lokalise: Translations update
  src/locale/en.json
Labels: lokalise

#1347 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1271 Updated topo.json for 2021 municipality changes
  package.json
  packages/app/gemeentecodes.json
  packages/app/generate-sitemap.js
  packages/app/src/components/choropleth/geography-simplified.topo.json
  packages/app/src/data/gemeente_veiligheidsregio.json
  packages/app/src/data/municipalCodeToRegionCodeLookup.ts
  packages/app/src/data/municipalSearchData.ts
  packages/app/src/data/regionCodeToMunicipalCodeLookup.ts
  packages/app/src/domain/layout/components/municipality-combo-box.tsx
  packages/app/src/static-props/municipality-data.ts
  packages/app/src/utils/getSafetyRegionForMunicipalityCode.ts
  packages/cli/src/validator/validate-all.ts
Labels: hold

#1348 Use infectious_people__estimate as difference key
  packages/app/schema/national/__difference.json
  packages/app/src/domain/layout/national-layout.tsx
  packages/app/src/pages/landelijk/besmettelijke-mensen.tsx
  packages/app/src/types/data.d.ts
Labels: hold

#1363 Lokalise: Translations update
  src/locale/en.json
  src/locale/nl.json
Labels: lokalise

#1364 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1366 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1367 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1371 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1374 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1375 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#1376 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#1378 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1380 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1381 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1389 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1395 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1398 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1399 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1401 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1402 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1413 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1416 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1423 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#1425 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1428 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1404 Replace hospital moving average with two new metric properties
  packages/app/cypress/integration/veiligheidsregio/ziekenhuis-opnames.spec.ts
  packages/app/schema/gm/__difference.json
  packages/app/schema/gm/hospital_nice.json
  packages/app/schema/gm_collection/hospital_nice.json
  packages/app/schema/nl/__difference.json
  packages/app/schema/nl/hospital_nice.json
  packages/app/schema/vr/__difference.json
  packages/app/schema/vr/hospital_nice.json
  packages/app/schema/vr_collection/hospital_nice.json
  packages/app/src/components/choropleth/municipal-thresholds.ts
  packages/app/src/components/choropleth/region-thresholds.ts
  packages/app/src/components/choropleth/tooltips/municipal/create-municipal-hospital-admissions-tooltip.tsx
  packages/app/src/components/choropleth/tooltips/region/create-region-hospital-admissions-tooltip.tsx
  packages/app/src/domain/layout/municipality-layout.tsx
  packages/app/src/domain/layout/national-layout.tsx
  packages/app/src/domain/layout/safety-region-layout.tsx
  packages/app/src/metric-config/nl.ts
  packages/app/src/pages/gemeente/[code]/ziekenhuis-opnames.tsx
  packages/app/src/pages/landelijk/ziekenhuis-opnames.tsx
  packages/app/src/pages/veiligheidsregio/[code]/ziekenhuis-opnames.tsx
  packages/app/src/types/data.d.ts
Labels: hold

#1452 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1453 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1462 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1494 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#1495 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#1502 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1503 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1508 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1512 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1514 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1516 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1517 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1518 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#1520 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1523 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1524 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1525 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1526 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1527 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1529 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1530 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1531 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1536 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1541 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#1548 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1549 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1550 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#1551 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#1553 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1554 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1566 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#1567 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#1573 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1574 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1335 Add vaccinatie page
  packages/app/src/assets/vaccinaties.svg
  packages/app/src/components-styled/kpi-value.tsx
  packages/app/src/domain/layout/national-layout.tsx
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
  packages/app/src/pages/landelijk/vaccinaties.tsx
  packages/app/src/utils/parse-markdown-in-locale.ts
Labels: hold

#1584 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1585 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1587 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1588 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1589 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1591 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#1592 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#1593 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1595 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1596 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1598 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1599 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1600 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1601 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#1603 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1608 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1609 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1611 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#1612 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1617 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1618 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1497 Add language switcher to CMS
  packages/app/src/pages/index.tsx
  packages/cms/hooks/helper/document-subject.js
  packages/cms/hooks/use-current-document.js
  packages/cms/language/supported-languages.js
  packages/cms/package.json
  packages/cms/plugins/translate/config.js
  packages/cms/plugins/translate/datastore.js
  packages/cms/plugins/translate/filter-fields.js
  packages/cms/plugins/translate/sanity.json
  packages/cms/plugins/translate/select-language-provider.js
  packages/cms/plugins/translate/select-language.js
  packages/cms/previews/resolve-production-url.js
  packages/cms/resolve-document-actions.js
  packages/cms/sanity.json
  packages/cms/schemas/locale/locale-block.js
  packages/cms/schemas/locale/locale-rich-content-block.js
  packages/cms/schemas/locale/locale-string.js
  packages/cms/schemas/locale/locale-text.js
  yarn.lock
Labels: enhancement

#1626 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1631 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1633 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1634 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1640 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1641 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1642 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1643 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1644 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1648 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1434 Export images from Sanity and resize them locally
  packages/app/.gitignore
  packages/app/package.json
  packages/app/src/components-styled/article-detail.tsx
  packages/app/src/components-styled/image.tsx
  packages/app/src/lib/sanity.tsx
  packages/app/src/pages/artikelen/[slug].tsx
  packages/app/src/types/cms.d.ts
  packages/app/src/utils/findClosestSize.ts
  packages/app/src/utils/imageLoader.ts
  packages/cms/.gitignore
  packages/cms/package.json
  packages/cms/scripts/images-download.sh
  packages/cms/scripts/images-resize.ts
  packages/common/src/config.ts
  packages/common/src/index.ts
  yarn.lock
Labels: WIP, enhancement, hold

#1650 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1651 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1653 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1654 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1656 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1655 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1657 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1660 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1661 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1663 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1669 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1676 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1607 Vaccine availability chart
  packages/app/package.json
  packages/app/src/components-styled/choropleth-legenda.tsx
  packages/app/src/components-styled/legenda.tsx
  packages/app/src/components-styled/line-chart/index.tsx
  packages/app/src/components-styled/stacked-chart/index.ts
  packages/app/src/components-styled/stacked-chart/logic.ts
  packages/app/src/components-styled/stacked-chart/stacked-chart.tsx
  packages/app/src/components/choropleth/municipality-choropleth.tsx
  packages/app/src/components/choropleth/municipality-navigation-map.tsx
  packages/app/src/components/choropleth/path.tsx
  packages/app/src/components/choropleth/region-thresholds.ts
  packages/app/src/components/choropleth/safety-region-choropleth.tsx
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
  packages/app/src/pages/landelijk/positief-geteste-mensen.tsx
  packages/app/src/pages/landelijk/vaccinaties.tsx
  packages/app/src/style/theme.ts
  packages/common/src/types/choropleth.ts
  packages/common/src/types/data.ts
  yarn.lock
Labels: hold

#1679 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1683 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1684 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1687 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1690 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1691 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1692 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1693 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1695 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1696 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1710 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1712 Lokalise: Translations update
  packages/app/src/locale/nl.json
Labels: lokalise

#1715 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1716 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1718 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1720 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1721 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1723 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1724 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1725 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1726 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise

#1727 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1728 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1729 Lokalise: Translations update
  packages/app/src/locale/en.json
Labels: lokalise

#1736 Lokalise: Translations update
  packages/app/src/locale/en.json
  packages/app/src/locale/nl.json
Labels: lokalise
